name: go test
on:   push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: willabides/setup-go-faster@v1
        with:
          go-version: '*'

      - name: Checkout
        uses: actions/checkout@v4

      - name: go build
        run:  go build -v

      - name: go test
        run:  go test ./...

      - name: go vet
        run:  go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
