name: go test
on:   push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'

      - name: Checkout
        uses: actions/checkout@v3

      - name: go test
        run:  go test ./...

      - name: go vet
        run:  go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
